apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-component-name
    app.kubernetes.io/part-of: application-sample
  name: component-sample
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: component-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: component-sample
    spec:
      containers:
      - image: docker.io/mm4eche/foobar:dev-code-with-quarkus-59b0823364ba05bd5a9d3a89d4e6cad57d2d3723
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
